# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generateCrossing <- function(aBidSignal, anAskSignal, aBidA, anAskA, aBidB, anAskB, theTheorPrice, theMargin, theStepback, theMarginInvA, theMarginInvB, theMarginInvSlope, theNormSigA, theNormSigB, theOrderLevelIncrementA, theOrderLevelIncrementB, enableSkew = FALSE) {
    .Call(`_quoterPkg_generateCrossing`, aBidSignal, anAskSignal, aBidA, anAskA, aBidB, anAskB, theTheorPrice, theMargin, theStepback, theMarginInvA, theMarginInvB, theMarginInvSlope, theNormSigA, theNormSigB, theOrderLevelIncrementA, theOrderLevelIncrementB, enableSkew)
}

computeDailyHedgedPnL <- function(bidA, askA, bidB, askB, aSellLevelA, aBuyLevelA, aSellLevelB, aBuyLevelB, orderVecA, orderVecB, minOrderSizeA, minOrderSizeB, tFeesMakerA, tFeesMakerB, tFeesTakerA, tFeesTakerB, idxEod, isDailyHedged) {
    .Call(`_quoterPkg_computeDailyHedgedPnL`, bidA, askA, bidB, askB, aSellLevelA, aBuyLevelA, aSellLevelB, aBuyLevelB, orderVecA, orderVecB, minOrderSizeA, minOrderSizeB, tFeesMakerA, tFeesMakerB, tFeesTakerA, tFeesTakerB, idxEod, isDailyHedged)
}

nc2lInventoryControl <- function(aBidA, anAskA, aBidB, anAskB, aSellLevelA, aBuyLevelA, aSellLevelB, aBuyLevelB, nc2l, aBaseOrderSizeA, aBaseOrderSizeB, growth_k = 0.5, max_mult = 3.0) {
    .Call(`_quoterPkg_nc2lInventoryControl`, aBidA, anAskA, aBidB, anAskB, aSellLevelA, aBuyLevelA, aSellLevelB, aBuyLevelB, nc2l, aBaseOrderSizeA, aBaseOrderSizeB, growth_k, max_mult)
}

