// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generateCrossing
List generateCrossing(NumericVector aBidSignal, NumericVector anAskSignal, NumericVector aBidA, NumericVector anAskA, NumericVector aBidB, NumericVector anAskB, double theTheorPrice, double theMargin, double theStepback, double theMarginInvA, double theMarginInvB, double theMarginInvSlope, double theNormSigA, double theNormSigB, double theOrderLevelIncrementA, double theOrderLevelIncrementB, bool enableSkew);
RcppExport SEXP _quoterPkg_generateCrossing(SEXP aBidSignalSEXP, SEXP anAskSignalSEXP, SEXP aBidASEXP, SEXP anAskASEXP, SEXP aBidBSEXP, SEXP anAskBSEXP, SEXP theTheorPriceSEXP, SEXP theMarginSEXP, SEXP theStepbackSEXP, SEXP theMarginInvASEXP, SEXP theMarginInvBSEXP, SEXP theMarginInvSlopeSEXP, SEXP theNormSigASEXP, SEXP theNormSigBSEXP, SEXP theOrderLevelIncrementASEXP, SEXP theOrderLevelIncrementBSEXP, SEXP enableSkewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type aBidSignal(aBidSignalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anAskSignal(anAskSignalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aBidA(aBidASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anAskA(anAskASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aBidB(aBidBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anAskB(anAskBSEXP);
    Rcpp::traits::input_parameter< double >::type theTheorPrice(theTheorPriceSEXP);
    Rcpp::traits::input_parameter< double >::type theMargin(theMarginSEXP);
    Rcpp::traits::input_parameter< double >::type theStepback(theStepbackSEXP);
    Rcpp::traits::input_parameter< double >::type theMarginInvA(theMarginInvASEXP);
    Rcpp::traits::input_parameter< double >::type theMarginInvB(theMarginInvBSEXP);
    Rcpp::traits::input_parameter< double >::type theMarginInvSlope(theMarginInvSlopeSEXP);
    Rcpp::traits::input_parameter< double >::type theNormSigA(theNormSigASEXP);
    Rcpp::traits::input_parameter< double >::type theNormSigB(theNormSigBSEXP);
    Rcpp::traits::input_parameter< double >::type theOrderLevelIncrementA(theOrderLevelIncrementASEXP);
    Rcpp::traits::input_parameter< double >::type theOrderLevelIncrementB(theOrderLevelIncrementBSEXP);
    Rcpp::traits::input_parameter< bool >::type enableSkew(enableSkewSEXP);
    rcpp_result_gen = Rcpp::wrap(generateCrossing(aBidSignal, anAskSignal, aBidA, anAskA, aBidB, anAskB, theTheorPrice, theMargin, theStepback, theMarginInvA, theMarginInvB, theMarginInvSlope, theNormSigA, theNormSigB, theOrderLevelIncrementA, theOrderLevelIncrementB, enableSkew));
    return rcpp_result_gen;
END_RCPP
}
// computeDailyHedgedPnL
List computeDailyHedgedPnL(NumericVector bidA, NumericVector askA, NumericVector bidB, NumericVector askB, NumericVector aSellLevelA, NumericVector aBuyLevelA, NumericVector aSellLevelB, NumericVector aBuyLevelB, NumericVector orderVecA, NumericVector orderVecB, double minOrderSizeA, double minOrderSizeB, double tFeesMakerA, double tFeesMakerB, double tFeesTakerA, double tFeesTakerB, IntegerVector idxEod, bool isDailyHedged);
RcppExport SEXP _quoterPkg_computeDailyHedgedPnL(SEXP bidASEXP, SEXP askASEXP, SEXP bidBSEXP, SEXP askBSEXP, SEXP aSellLevelASEXP, SEXP aBuyLevelASEXP, SEXP aSellLevelBSEXP, SEXP aBuyLevelBSEXP, SEXP orderVecASEXP, SEXP orderVecBSEXP, SEXP minOrderSizeASEXP, SEXP minOrderSizeBSEXP, SEXP tFeesMakerASEXP, SEXP tFeesMakerBSEXP, SEXP tFeesTakerASEXP, SEXP tFeesTakerBSEXP, SEXP idxEodSEXP, SEXP isDailyHedgedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bidA(bidASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type askA(askASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bidB(bidBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type askB(askBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aSellLevelA(aSellLevelASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aBuyLevelA(aBuyLevelASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aSellLevelB(aSellLevelBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aBuyLevelB(aBuyLevelBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type orderVecA(orderVecASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type orderVecB(orderVecBSEXP);
    Rcpp::traits::input_parameter< double >::type minOrderSizeA(minOrderSizeASEXP);
    Rcpp::traits::input_parameter< double >::type minOrderSizeB(minOrderSizeBSEXP);
    Rcpp::traits::input_parameter< double >::type tFeesMakerA(tFeesMakerASEXP);
    Rcpp::traits::input_parameter< double >::type tFeesMakerB(tFeesMakerBSEXP);
    Rcpp::traits::input_parameter< double >::type tFeesTakerA(tFeesTakerASEXP);
    Rcpp::traits::input_parameter< double >::type tFeesTakerB(tFeesTakerBSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idxEod(idxEodSEXP);
    Rcpp::traits::input_parameter< bool >::type isDailyHedged(isDailyHedgedSEXP);
    rcpp_result_gen = Rcpp::wrap(computeDailyHedgedPnL(bidA, askA, bidB, askB, aSellLevelA, aBuyLevelA, aSellLevelB, aBuyLevelB, orderVecA, orderVecB, minOrderSizeA, minOrderSizeB, tFeesMakerA, tFeesMakerB, tFeesTakerA, tFeesTakerB, idxEod, isDailyHedged));
    return rcpp_result_gen;
END_RCPP
}
// nc2lInventoryControl
List nc2lInventoryControl(NumericVector aBidA, NumericVector anAskA, NumericVector aBidB, NumericVector anAskB, NumericVector aSellLevelA, NumericVector aBuyLevelA, NumericVector aSellLevelB, NumericVector aBuyLevelB, int nc2l, double aBaseOrderSizeA, double aBaseOrderSizeB, double growth_k, double max_mult);
RcppExport SEXP _quoterPkg_nc2lInventoryControl(SEXP aBidASEXP, SEXP anAskASEXP, SEXP aBidBSEXP, SEXP anAskBSEXP, SEXP aSellLevelASEXP, SEXP aBuyLevelASEXP, SEXP aSellLevelBSEXP, SEXP aBuyLevelBSEXP, SEXP nc2lSEXP, SEXP aBaseOrderSizeASEXP, SEXP aBaseOrderSizeBSEXP, SEXP growth_kSEXP, SEXP max_multSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type aBidA(aBidASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anAskA(anAskASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aBidB(aBidBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anAskB(anAskBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aSellLevelA(aSellLevelASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aBuyLevelA(aBuyLevelASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aSellLevelB(aSellLevelBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aBuyLevelB(aBuyLevelBSEXP);
    Rcpp::traits::input_parameter< int >::type nc2l(nc2lSEXP);
    Rcpp::traits::input_parameter< double >::type aBaseOrderSizeA(aBaseOrderSizeASEXP);
    Rcpp::traits::input_parameter< double >::type aBaseOrderSizeB(aBaseOrderSizeBSEXP);
    Rcpp::traits::input_parameter< double >::type growth_k(growth_kSEXP);
    Rcpp::traits::input_parameter< double >::type max_mult(max_multSEXP);
    rcpp_result_gen = Rcpp::wrap(nc2lInventoryControl(aBidA, anAskA, aBidB, anAskB, aSellLevelA, aBuyLevelA, aSellLevelB, aBuyLevelB, nc2l, aBaseOrderSizeA, aBaseOrderSizeB, growth_k, max_mult));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_quoterPkg_generateCrossing", (DL_FUNC) &_quoterPkg_generateCrossing, 17},
    {"_quoterPkg_computeDailyHedgedPnL", (DL_FUNC) &_quoterPkg_computeDailyHedgedPnL, 18},
    {"_quoterPkg_nc2lInventoryControl", (DL_FUNC) &_quoterPkg_nc2lInventoryControl, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_quoterPkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
